<img src="http://cfs22.simplicdn.net/ice9/new_logo.svgz "/>

# Assignment 02: Evaluate the Diabetes Dataset

*The comments/sections provided are your cues to perform the assignment. You don't need to limit yourself to the number of rows/cells provided. You can add additional rows in each section to add more lines of code.*

*If at any point in time you need help on solving this assignment, view our demo video to understand the different steps of the code.*

**Happy coding!**

* * *

#### 1: Import the dataset

In [1]:
#Import the required libraries
import pandas as pd
import numpy as np

In [2]:
#Import the diabetes dataset
df_data = pd.read_csv('pima-indians-diabetes.data', header = None)

#### 2: Analyze the dataset

In [3]:
#View the first five observations of the dataset
df_data.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

#### 3: Find the features of the dataset

In [4]:
#Use the .NAMES file to view and set the features of the dataset
feature_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']

In [5]:
#Use the feature names set earlier and fix it as the column headers of the dataset
df_data = pd.read_csv('pima-indians-diabetes.data', header = None, names = feature_names)

In [6]:
#Verify if the dataset is updated with the new headers
df_data.head()

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1

In [7]:
#View the number of observations and features of the dataset
df_data.shape

(768, 9)

#### 4: Find the response  of the dataset

In [8]:
#Select features from the dataset to create the model
feature_selection = df_data.drop('label', axis = 1)

In [9]:
#Create the feature object
X = feature_selection

In [10]:
#Create the reponse object
y = df_data['label']

In [11]:
#View the shape of the feature object
X.shape

(768, 8)

In [12]:
#View the shape of the target object
y.shape

(768,)

#### 5: Use training and testing datasets to train the model

In [13]:
#Split the dataset to test and train the model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

#### 6: Create a model  to predict the diabetes outcome

In [14]:
# Create a logistic regression model using the training set
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression()
logReg.fit(X_train, y_train)

C:\Users\Chacha Tech\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
#Make predictions using the testing set
y_pred = logReg.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

#### 7: Check the accuracy of the model

In [16]:
#Evaluate the accuracy of your model
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7291666666666666

In [17]:
#Print the first 30 actual and predicted responses
print("Top 30 Actual Responses : \n", y_test.values[0:30])
print("Top 30 Predicted Responses : \n", y_pred[0:30])

Top 30 Actual Responses : 
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0]
Top 30 Predicted Responses : 
 [0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0]
